name: CI With Token

on: [workflow_dispatch]

jobs:
  sample_build:
    runs-on: azure-runners
    steps:
      - name: "rate limit"
        run: |
          curl \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token $TOKEN" \
            https://api.github.com/rate_limit
        env:
          TOKEN: ${{ secrets.PERSONAL_TOKEN }}

      - name: Clear the tool cache
        run: rm -rf /Users/runner/hostedtoolcache/Python/

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          python-version: 3.9.12

      - name: "rate limit"
        run: |
          curl \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token $TOKEN" \
            https://api.github.com/rate_limit
        env:
          TOKEN: ${{ secrets.PERSONAL_TOKEN }}
