name: delete

on:
  workflow_dispatch:
  delete:

env:           
  DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
  DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

jobs:
  on-push:
    runs-on: azure-runners
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install databricks cli
        run: pip install databricks-cli==0.17.*
      - name: Check if repo exists
        run: databricks repos delete --path "/Repos/${{ github.event.repository.name }}/${{ github.event.ref }}"
